version: '3.7'

services:
  spark-master:
    image: spark-master
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
       - /opt/spark/apps:/opt/spark-apps
       - /opt/spark/data:/opt/spark-data
    networks:
      - spark-network

  spark-worker:
    image: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=4
      - SPARK_WORKER_MEMORY=2G
    volumes:
       - /opt/spark/apps:/opt/spark-apps
       - /opt/spark/data:/opt/spark-data
    networks:
      - spark-network
    deploy:
      mode: replicated
      replicas: 3
  
networks:
  spark-network:
